# Generated by Django 4.2.16 on 2024-11-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
    ]
