# Generated by Django 4.2.16 on 2025-01-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['order']},
        ),
    ]
